In [8]:
print('Hello World')

Hello World


In [7]:
import numpy as np # to create and manipulate arrays and matrices

In [50]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [51]:
np.array(my_list) # turning a list into an array

array([1, 2, 3])

In [52]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [53]:
np.array(my_matrix) # 2D array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
my_3d_list = [[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]],[[1,2,3],[4,5,6],[7,8,9]]] # 3D lists
np.array(my_3d_list)

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [55]:
np.arange(0,10,2) # creating an array witht the range(0,10) and 2 step

array([0, 2, 4, 6, 8])

In [56]:
np.zeros((3,3,3)) # create a array with zeros, each comma adds a dimension below is a 3D array # zeros can be changed to ones 

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [57]:
np.eye(4)# creation of an array using linear algebra

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [58]:
np.linspace(0,10,3) # range(0,10) and perfectly split by 3

array([ 0.,  5., 10.])

In [60]:
np.random.rand(2,2,2) # create an array of 2 random numbers again each "," adds a dimension

array([[[0.37198069, 0.9877202 ],
        [0.81014642, 0.07505186]],

       [[0.81138171, 0.53694274],
        [0.39351908, 0.78464442]]])

In [62]:
np.random.randint(0,100,10) # array of 10 random integers in range(0,100) 

array([ 6, 54, 68, 46, 78, 27, 59, 76, 22, 78])

In [64]:
my_3d_array = np.array(my_3d_list)
my_3d_array.shape # showing the dimensional specs 

(3, 3, 3)

In [66]:
x = np.arange(0,27)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [70]:
x.reshape(3,3,3) # reshaping an array to new dimensional structures

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [71]:
x.reshape(3,3,3).reshape(-1) # inputing -1 will revert the initial reshape

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [85]:
array_3d = x.reshape(3,3,3)

In [82]:
array_3d.max()

26

In [81]:
array_3d.min()

0

In [80]:
array_3d.argmax() # show the position of the max value

26

In [125]:
np.argmin(array_3d, axis = 1)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [118]:
np.argmax(arr_2d,axis = 0)

array([2, 2, 2])

In [79]:
array_3d.argmin() # show the position of the min value

0

In [86]:
array_3d.dtype # show data types

dtype('int64')

In [87]:
array_3d.ndim # get the dimension of the array

3

In [99]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
arr[8]

8

In [90]:
arr[1:5] # slice of index[1] to [5]

array([1, 2, 3, 4])

In [91]:
arr[0:10:2] # call index from [0] to [10] in steps of 2

array([0, 2, 4, 6, 8])

In [101]:
arr_2 = arr.copy()
arr_2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
arr_2[::2] = 100 # change to 100 in steps of 2
arr_2

array([100,   1, 100,   3, 100,   5, 100,   7, 100,   9, 100])

In [105]:
arr_2d = np.arange(0,9).reshape(3,3)
arr_2d

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [106]:
arr_2d[0] #call a row

array([0, 1, 2])

In [107]:
arr_2d[0][2] # call index(0,2)

2

In [110]:
arr_2d[:2,1:] # slicing top right corner :2 for 1st and 2nd object then 1: the second and last object

array([[1, 2],
       [4, 5]])

In [111]:
arr_2d[:,2] # slice y axis select whole list and only return its end value (2)

array([2, 5, 8])

In [113]:
arr[[2,5,9]]# fancy indexing, the orders can be mixed

array([2, 5, 9])

In [114]:
arr_2d[[0,2]] # indexing first row and last row

array([[0, 1, 2],
       [6, 7, 8]])

In [115]:
arr < 8 # returns the booleans value of the condition

array([ True,  True,  True,  True,  True,  True,  True,  True, False,
       False, False])

In [116]:
arr[arr < 8] # return values where conditions are true

array([0, 1, 2, 3, 4, 5, 6, 7])